name: Test and push to wiki

on:
  push:
    branches:
      - main
      - prettier
  workflow_dispatch:
    inputs:
      deploy:
        description: "Push to main wiki"
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  prettier:
    name: Validate formatting with prettier
    strategy:
      fail-fast: true
    continue-on-error: false
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0
      - name: add wiki push destination
        if: github.ref_name == github.event.repository.default_branch
        run: |
          git remote set-url --add --push origin git@github.com:SickChill/SickChill.WikiTemp.wiki.git
      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          dry: ${{ github.ref_name == github.event.repository.default_branch }}
          push_options: -f
          prettier_options: --write **/*.{js,md}
  deploy:
    name: Deploy to main wiki
    strategy:
      fail-fast: true
    continue-on-error: false
    needs: prettier
    runs-on: ubuntu-22.04
    env:
      WIKIDIR: ./upstream
    if: ${{ github.event.inputs.deploy }}
    steps:
      - name: Checkout Upstream
        uses: actions/checkout@v3
        with:
          repository: SickChill/sickchill.wiki
          token: ${{ secrets.SICKCHILL_TOK }}
          path: ${{ env.WIKIDIR }}
          ref: master
          fetch-depth: 0
      - name: Push wikitemp to upstream wiki 
        run: |
          git remote add wikitemp git@github.com:SickChill/SickChill.WikiTemp.git
          git fetch wikitemp
          git reset --hard wikitemp/${{ github.ref_name }}
          git push origin -f master
        working-directory: ${{ env.WIKIDIR }}
          
