name: Test and push to wiki

on:
  push:
    branches:
      - main
      - prettier

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  prettier:
    strategy:
      fail-fast: true
    continue-on-error: false
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.ref_name }}
          fetch-depth: 0
      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --check **/*.{js,md}
      - name: Push to wiki
        if: github.ref_name == github.event.repository.default_branch
        run: |
          git remote add wiki git@github.com:SickChill/SickChill.WikiTemp.wiki.git
          git push wiki ${{ github.ref_name }} -f
