name: Test and push to wiki

on:
  push:
    branches:
      - main
      - prettier

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  prettier:
    strategy:
      fail-fast: true
    continue-on-error: false
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.ref_name }}
          fetch-depth: 0
      - name: Add push urls
        run: |
          git remote set-url --add --push origin git@github.com:SickChill/SickChill.wiki.git
          git remote set-url --add --push origin git@github.com:SickChill/SickChill.WikiTemp.wiki.git
      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          dry: ${{github.ref_name == github.event.repository.default_branch}}
          push_options: -f
          prettier_options: --write **/*.{js,md}
